# Generated by Django 5.0.3 on 2024-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland', 'Newfoundland'), ('Nova Scotia', 'Nova Scotia'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Yukon', 'Yukon')], max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('crop_type', models.CharField(choices=[('Field crops (grains or beans)', 'Field crops (grains or beans)'), ('Flowers', 'Flowers'), ('Fruit/berries/grapes', 'Fruit/berries/grapes'), ('Hay or forage crops', 'Hay or forage crops'), ('Herbs', 'Herbs'), ('Livestock', 'Livestock'), ('Seeds, seedlings or nursery stock', 'Seeds, seedlings or nursery stock'), ('Vegetables', 'Vegetables'), ('Other products', 'Other products')], max_length=100, null=True)),
                ('min_renting_period', models.PositiveIntegerField()),
            ],
        ),
    ]
